### ISSUE TITLE
prints out the ASCII in multiple message boxes,

### ISSUE THREAD

**Issue by WK-GiHu** [DeathResister/ASCII-RLE#5]
.... but still does not work properly; It now prints out the ASCII in multiple message boxes, leaving the user with a very annoying time having to click OK multiple times and the image appearing completely wrong. It there a way to fix this?

_Originally posted by @DeathResister in https://github.com/DeathResister/ASCII-RLE/issues/4#issuecomment-579827897_

**Comment by WK-GiHu** [comment]
@DeathResister 

> multiple message boxes

Move line 147
https://github.com/DeathResister/ASCII-RLE/blob/1cff9a6fd469e9c99480ca34ec359ae041f5a359/Frames%20-%20Tkinter.py#L147
before line 146
https://github.com/DeathResister/ASCII-RLE/blob/1cff9a6fd469e9c99480ca34ec359ae041f5a359/Frames%20-%20Tkinter.py#L146

---

Outdent line 151
https://github.com/DeathResister/ASCII-RLE/blob/1cff9a6fd469e9c99480ca34ec359ae041f5a359/Frames%20-%20Tkinter.py#L151
to the level of line 146
https://github.com/DeathResister/ASCII-RLE/blob/1cff9a6fd469e9c99480ca34ec359ae041f5a359/Frames%20-%20Tkinter.py#L146

**Comment by DeathResister** [comment]
Wow, now it just shows it as a long message box (tall), making the 'art' unrecognisable.

Maybe going about this via message box is not the right thing?, What do you suggest because at the moment it's not going the direction I hoped.

Just for clarification the LogoRLE **IS** the compressed version of the LogoASCII so how can we present it like the LogoASCII
